### ISSUE TITLE
Uncaught ArgumentCountError: Too few arguments to function ganglia_api_error_handler(),

### ISSUE THREAD

**Issue by rica01** [ganglia/ganglia-web#384]
Out of a fresh install on ubuntu 22.04

`PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function ganglia_api_error_handler(), 4 passed in /usr/share/ganglia-webfrontend/ganglia.php on line 353 and exactly 5 expected in /usr/share/ganglia-webfrontend/lib/common_api.php:18\nStack trace:\n#0 /usr/share/ganglia-webfrontend/ganglia.php(353): ganglia_api_error_handler()\n#1 /usr/share/ganglia-webfrontend/get_ganglia.php(11): Gmetad()\n#2 /usr/share/ganglia-webfrontend/index.php(7): include_once('...')\n#3 {main}\n  thrown in /usr/share/ganglia-webfrontend/lib/common_api.php on line 18
`

with:
Apache/2.4.52 (Ubuntu)
PHP 8.1.2-1ubuntu2.20
gmetad/gmond 3.7.2-6
ganglia-webfrontend 3.7.5+debian-4

**Comment by OpenSourceMasters** [comment]
I have the same issue on Ubuntu 24.04.2 LTS.  I just installed ganglia-webfrontend on a fresh installed machine and when I hit the frontend at /ganglia, I get this same php:error in apache error logs.

**Comment by yyu233** [comment]
> I have the same issue on Ubuntu 24.04.2 LTS. I just installed ganglia-webfrontend on a fresh installed machine and when I hit the frontend at /ganglia, I get this same php:error in apache error logs.

> I have the same issue.

@ondrejch @OpenSourceMasters 
Replaced with this version of common_api.php works for me
https://github.com/ganglia/ganglia-web/blob/master/lib/common_api.php

**Comment by rica01** [comment]
tried what @yyu233 said different error shows up:


`[Mon Nov 24 14:08:47.022552 2025] [php:error] [pid 10307] [client 10.205.215.126:41662] PHP Fatal error:  Uncaught TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given in /usr/share/ganglia-webfrontend/ganglia.php:353\nStack trace:\n#0 /usr/share/ganglia-webfrontend/ganglia.php(353): in_array()\n#1 /usr/share/ganglia-webfrontend/get_ganglia.php(11): Gmetad()\n#2 /usr/share/ganglia-webfrontend/index.php(7): include_once('...')\n#3 {main}\n  thrown in /usr/share/ganglia-webfrontend/ganglia.php on line 353`
